# Generated by Django 3.0.5 on 2020-04-13 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('academic_year', models.IntegerField(default=2020)),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('status', models.CharField(default='active', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(default='', max_length=30, unique=True)),
                ('year_of_enrollment', models.IntegerField(default=2020)),
                ('program', models.CharField(default='BTech', max_length=30)),
                ('status', models.CharField(blank=True, default='active', max_length=30)),
                ('gender', models.CharField(default='male', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(default='', max_length=30, unique=True, verbose_name='Faculty ID')),
                ('dept', models.CharField(default='', max_length=50, verbose_name='Department')),
                ('status', models.CharField(blank=True, default='active', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
