# Generated by Django 3.0.5 on 2020-04-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('faculty_primary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='attendence.Faculty')),
                ('faculty_secondary', models.ManyToManyField(related_name='courses_secondary', to='attendence.Faculty')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='attendence.Semester')),
            ],
        ),
    ]
