# Generated by Django 3.0.5 on 2020-04-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='dept',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='fid',
            new_name='faculty_id',
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
