# Generated by Django 3.0.5 on 2020-04-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_auto_20200415_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty_secondary',
            field=models.ManyToManyField(null=True, related_name='courses_secondary', to='attendence.Faculty'),
        ),
    ]
