# Generated by Django 3.0.5 on 2020-04-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0007_auto_20200415_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day1',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='day2',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default='', max_length=10),
        ),
    ]
