# Generated by Django 3.0.5 on 2020-04-15 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0009_auto_20200415_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='active', max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_entries', to='attendence.Course')),
            ],
        ),
    ]
