# Generated by Django 3.0.5 on 2020-04-17 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendence', '0010_courseentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=20, unique=True)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('term', models.CharField(choices=[('', ''), ('spring', 'Spring'), ('monsoon', 'Monsoon'), ('summer', 'Summer')], default='', max_length=10)),
                ('day1', models.CharField(blank=True, choices=[('', ''), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default='', max_length=10)),
                ('day2', models.CharField(blank=True, choices=[('', ''), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='day1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='day2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='courseentry',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseentry',
            name='students_attended',
            field=models.ManyToManyField(blank=True, related_name='course_entries', to='attendence.Student'),
        ),
        migrations.AddField(
            model_name='semester',
            name='students_enrolled',
            field=models.ManyToManyField(blank=True, related_name='semsters', to='attendence.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='course_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='attendence.CourseDetail'),
        ),
    ]
