# Generated by Django 3.0.5 on 2020-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0011_auto_20200417_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='category',
            field=models.CharField(choices=[('', ''), ('fulltime', 'Full Time'), ('parttime', 'Part Time'), ('guest', 'Guest')], default='', max_length=50),
        ),
    ]
