# Generated by Django 3.0.5 on 2020-04-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0012_auto_20200419_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseentry',
            name='status',
            field=models.CharField(default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='status',
            field=models.CharField(default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=30),
        ),
    ]
