# Generated by Django 3.0.5 on 2020-04-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0013_auto_20200419_2133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseEntry',
            new_name='Class',
        ),
    ]
