# Generated by Django 3.0.5 on 2020-04-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0014_auto_20200423_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='attendence.Student'),
        ),
    ]
